### ISSUE TITLE
Improve Error Message When Accessing Property Out of Range

### ISSUE THREAD

**Issue by sisbell** [sisbell/stackwire-gpt#56]
In the project.yaml, if the properties try to index a value greater than the size of the property array, there is a Range Error thrown. This is not a helpful error message. Replace this error with something more intelligible.

```
        import:
          propertiesFile: properties.json
          properties:
            rank: 3
            show: 2
```
 
```
 RangeError (index): Invalid value: Only valid value is 0: 1
  dart:core                           List.[]
  package:gpt/src/prompts.dart 38:52  createPromptByIndex.<fn>
  dart:core                           _StringBase.replaceAllMapped
  package:gpt/src/prompts.dart 37:38  createPromptByIndex
  test/prompts_test.dart 50:22        main.<fn>.<fn>
```
